### ISSUE TITLE
how to run deploy function

### ISSUE THREAD

**Issue by harryhazza77** [rhythminme/serverless-gulp#4]
Hi,

is there a way of running the equivalent of 
> sls deploy function --function myFunction

**Comment by murilodag** [comment]
@harryhazza77 did you find a way to deploy a single function?

**Comment by murilodag** [comment]
Hello @harryhazza77, vitor's PR should fix it.

**Comment by rajwilkhu** [comment]
@harryhazza77 can you give vitor's changes a go and re-open if you need something specific?

**Comment by harryhazza77** [comment]
thanks guys, will do.
